import React, { createContext, useContext, useState } from 'react';

export interface VideoData {
    id: string;
    title: string;
    description: string;
    videoUrl: string;
    thumbnailUrl?: string;
    stats: {
        duration: string;
        quality: string;
        delivery: string;
    };
    features: string[];
}

interface VideoContextType {
    videos: Record<string, VideoData>;
    updateVideo: (id: string, data: Partial<VideoData>) => void;
    saveVideo: () => { success: boolean; error?: string };
}

const defaultVideos: Record<string, VideoData> = {
    'chat-agents': {
        id: 'chat-agents',
        title: 'Chat Agents',
        description: 'Intelligent WhatsApp chatbots that seamlessly interact with humans, providing instant support and engagement.',
        videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-virtual-reality-game-display-1167-large.mp4', // Placeholder
        stats: { duration: '24/7', quality: 'Auto', delivery: 'Instant' },
        features: ['Natural Language Processing', 'Multi-language Support', 'Automated Workflows', 'CRM Integration']
    },
    'ai-avatars': {
        id: 'ai-avatars',
        title: 'AI Avatars',
        description: 'Lifelike AI avatars that can present your content with human-like expressions and gestures.',
        videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-woman-wearing-a-vr-headset-interacting-with-data-43687-large.mp4', // Placeholder
        stats: { duration: 'Custom', quality: '4K', delivery: '24 Hours' },
        features: ['Photorealistic Rendering', 'Customizable Appearance', 'Lip-sync Technology', 'Brand Consistency']
    },
    'video-ads': {
        id: 'video-ads',
        title: 'AI Generated Video Ads',
        description: 'High-converting video advertisements generated by AI, tailored to your target audience.',
        videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-digital-animation-of-a-city-interface-965-large.mp4', // Placeholder
        stats: { duration: '15-60s', quality: '1080p', delivery: '48 Hours' },
        features: ['Targeted Messaging', 'A/B Testing Ready', 'Viral Potential', 'Cost-Effective']
    },
    'voice-agents': {
        id: 'voice-agents',
        title: 'Voice Calling Agents',
        description: 'Sophisticated voice agents capable of handling complex customer conversations over the phone.',
        videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-customer-service-woman-working-on-computer-43682-large.mp4', // Placeholder
        stats: { duration: 'Unlimited', quality: 'HD Voice', delivery: 'Real-time' },
        features: ['Sentiment Analysis', 'Context Awareness', 'Seamless Handoff', 'Call Recording']
    }
};

const VideoContext = createContext<VideoContextType | undefined>(undefined);

export function VideoProvider({ children }: { children: React.ReactNode }) {
    const [videos, setVideos] = useState<Record<string, VideoData>>(() => {
        const saved = localStorage.getItem('siwaht_videos');
        if (saved) {
            try {
                const parsed = JSON.parse(saved);
                const merged = { ...defaultVideos };

                Object.keys(defaultVideos).forEach(key => {
                    if (parsed[key]) {
                        merged[key] = {
                            ...defaultVideos[key],
                            ...parsed[key],
                            // Deep merge stats
                            stats: {
                                ...defaultVideos[key].stats,
                                ...(parsed[key].stats || {})
                            }
                        };
                    }
                });
                return merged;
            } catch (error) {
                console.error('Failed to parse saved videos:', error);
                return defaultVideos;
            }
        }
        return defaultVideos;
    });

    // Save ALL videos to localStorage
    const persistToStorage = (allVideos: Record<string, VideoData>) => {
        localStorage.setItem('siwaht_videos', JSON.stringify(allVideos));
    };

    const updateVideo = (id: string, data: Partial<VideoData>) => {
        setVideos(prev => {
            const updated = {
                ...prev,
                [id]: { ...prev[id], ...data }
            };
            // Logic: Do we want to save on every change? 
            // The user says "not getting saved", so maybe explicit save is better.
            // But let's keep it sync'd for now but maybe debounce?
            // Actually, let's just make sure Save button works perfectly.
            return updated;
        });
    };

    const saveVideo = (): { success: boolean; error?: string } => {
        try {
            // We use the current latest state 'videos'
            persistToStorage(videos);
            return { success: true };
        } catch (error) {
            console.error('Error saving video:', error);
            return {
                success: false,
                error: error instanceof Error ? error.message : 'Failed to save video'
            };
        }
    };

    return (
        <VideoContext.Provider value={{ videos, updateVideo, saveVideo }}>
            {children}
        </VideoContext.Provider>
    );
}

export function useVideos() {
    const context = useContext(VideoContext);
    if (context === undefined) {
        throw new Error('useVideos must be used within a VideoProvider');
    }
    return context;
}
