import React, { createContext, useContext, useState, useCallback, useRef, useEffect } from 'react';

export interface VideoData {
    id: string;
    title: string;
    description: string;
    videoUrl: string;
    thumbnailUrl?: string;
    stats: {
        duration: string;
        quality: string;
        delivery: string;
    };
    features: string[];
}

interface VideoContextType {
    videos: Record<string, VideoData>;
    updateVideo: (id: string, data: Partial<VideoData>) => void;
    updateAndSaveVideo: (id: string, data: Partial<VideoData>) => { success: boolean; error?: string };
}

const STORAGE_KEY = 'siwaht_videos';
const STORAGE_VERSION = 'v3'; // Bump this to force refresh of defaults

const defaultVideos: Record<string, VideoData> = {
    'chat-agents': {
        id: 'chat-agents',
        title: 'Chat Agents',
        description: 'Intelligent WhatsApp chatbots that seamlessly interact with humans, providing instant support and engagement.',
        videoUrl: 'https://gumlet.tv/watch/694c0aa2b122cbf1763c9e71',
        stats: { duration: '24/7', quality: 'Auto', delivery: 'Instant' },
        features: ['Natural Language Processing', 'Multi-language Support', 'Automated Workflows', 'CRM Integration']
    },
    'ai-avatars': {
        id: 'ai-avatars',
        title: 'AI Avatars',
        description: 'Lifelike AI avatars that can present your content with human-like expressions and gestures.',
        videoUrl: 'https://gumlet.tv/watch/694c0f24b122cbf1763ce88c',
        stats: { duration: 'Custom', quality: '4K', delivery: '24 Hours' },
        features: ['Photorealistic Rendering', 'Customizable Appearance', 'Lip-sync Technology', 'Brand Consistency']
    },
    'video-ads': {
        id: 'video-ads',
        title: 'AI Generated Video Ads',
        description: 'High-converting video advertisements generated by AI, tailored to your target audience.',
        videoUrl: 'https://gumlet.tv/watch/694bfeb6b122cbf1763bdd74',
        stats: { duration: '15-60s', quality: '1080p', delivery: '48 Hours' },
        features: ['Targeted Messaging', 'A/B Testing Ready', 'Viral Potential', 'Cost-Effective']
    },
    'voice-agents': {
        id: 'voice-agents',
        title: 'Voice Calling Agents',
        description: 'Sophisticated voice agents capable of handling complex customer conversations over the phone.',
        videoUrl: 'https://gumlet.tv/watch/694c0f24b122cbf1763ce88c',
        stats: { duration: 'Unlimited', quality: 'HD Voice', delivery: 'Real-time' },
        features: ['Sentiment Analysis', 'Context Awareness', 'Seamless Handoff', 'Call Recording']
    }
};

const loadVideosFromStorage = (): Record<string, VideoData> => {
    try {
        // Check version - if outdated, clear and use new defaults
        const version = localStorage.getItem(`${STORAGE_KEY}_version`);
        if (version !== STORAGE_VERSION) {
            localStorage.removeItem(STORAGE_KEY);
            localStorage.setItem(`${STORAGE_KEY}_version`, STORAGE_VERSION);
            return defaultVideos;
        }

        const saved = localStorage.getItem(STORAGE_KEY);
        if (saved) {
            const parsed = JSON.parse(saved);
            const merged = { ...defaultVideos };

            Object.keys(defaultVideos).forEach(key => {
                if (parsed[key]) {
                    merged[key] = {
                        ...defaultVideos[key],
                        ...parsed[key],
                        stats: {
                            ...defaultVideos[key].stats,
                            ...(parsed[key].stats || {})
                        }
                    };
                }
            });
            return merged;
        }
    } catch (error) {
        console.error('Failed to parse saved videos:', error);
    }
    return defaultVideos;
};

const saveVideosToStorage = (videos: Record<string, VideoData>): { success: boolean; error?: string } => {
    try {
        localStorage.setItem(STORAGE_KEY, JSON.stringify(videos));
        return { success: true };
    } catch (error) {
        console.error('Error saving videos to localStorage:', error);
        return {
            success: false,
            error: error instanceof Error ? error.message : 'Failed to save video'
        };
    }
};

const VideoContext = createContext<VideoContextType | undefined>(undefined);

export function VideoProvider({ children }: { children: React.ReactNode }) {
    const [videos, setVideos] = useState<Record<string, VideoData>>(loadVideosFromStorage);
    const videosRef = useRef(videos);

    // Keep ref in sync with state
    useEffect(() => {
        videosRef.current = videos;
    }, [videos]);

    const updateVideo = useCallback((id: string, data: Partial<VideoData>) => {
        setVideos(prev => ({
            ...prev,
            [id]: { ...prev[id], ...data }
        }));
    }, []);

    // Combined update and save - solves the stale state issue
    const updateAndSaveVideo = useCallback((id: string, data: Partial<VideoData>): { success: boolean; error?: string } => {
        const currentVideos = videosRef.current;
        const updatedVideos = {
            ...currentVideos,
            [id]: { ...currentVideos[id], ...data }
        };
        
        // Update state
        setVideos(updatedVideos);
        
        // Save to localStorage immediately with the new data
        return saveVideosToStorage(updatedVideos);
    }, []);

    return (
        <VideoContext.Provider value={{ videos, updateVideo, updateAndSaveVideo }}>
            {children}
        </VideoContext.Provider>
    );
}

export function useVideos() {
    const context = useContext(VideoContext);
    if (context === undefined) {
        throw new Error('useVideos must be used within a VideoProvider');
    }
    return context;
}
