import React, { createContext, useContext, useState, useEffect } from 'react';
import { supabase } from '../lib/supabase';

export interface VideoData {
    id: string;
    title: string;
    description: string;
    videoUrl: string;
    thumbnailUrl?: string;
    stats: {
        duration: string;
        quality: string;
        delivery: string;
    };
    features: string[];
}

interface VideoContextType {
    videos: Record<string, VideoData>;
    updateVideo: (id: string, data: Partial<VideoData>) => void;
    saveVideo: (id: string, data?: Partial<VideoData>) => Promise<{ success: boolean; error?: string }>;
    loading: boolean;
}

const defaultVideos: Record<string, VideoData> = {
    'chat-agents': {
        id: 'chat-agents',
        title: 'Chat Agents',
        description: 'Intelligent WhatsApp chatbots that seamlessly interact with humans, providing instant support and engagement.',
        videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-virtual-reality-game-display-1167-large.mp4', // Placeholder
        stats: { duration: '24/7', quality: 'Auto', delivery: 'Instant' },
        features: ['Natural Language Processing', 'Multi-language Support', 'Automated Workflows', 'CRM Integration']
    },
    'ai-avatars': {
        id: 'ai-avatars',
        title: 'AI Avatars',
        description: 'Lifelike AI avatars that can present your content with human-like expressions and gestures.',
        videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-woman-wearing-a-vr-headset-interacting-with-data-43687-large.mp4', // Placeholder
        stats: { duration: 'Custom', quality: '4K', delivery: '24 Hours' },
        features: ['Photorealistic Rendering', 'Customizable Appearance', 'Lip-sync Technology', 'Brand Consistency']
    },
    'video-ads': {
        id: 'video-ads',
        title: 'AI Generated Video Ads',
        description: 'High-converting video advertisements generated by AI, tailored to your target audience.',
        videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-digital-animation-of-a-city-interface-965-large.mp4', // Placeholder
        stats: { duration: '15-60s', quality: '1080p', delivery: '48 Hours' },
        features: ['Targeted Messaging', 'A/B Testing Ready', 'Viral Potential', 'Cost-Effective']
    },
    'voice-agents': {
        id: 'voice-agents',
        title: 'Voice Calling Agents',
        description: 'Sophisticated voice agents capable of handling complex customer conversations over the phone.',
        videoUrl: 'https://assets.mixkit.co/videos/preview/mixkit-customer-service-woman-working-on-computer-43682-large.mp4', // Placeholder
        stats: { duration: 'Unlimited', quality: 'HD Voice', delivery: 'Real-time' },
        features: ['Sentiment Analysis', 'Context Awareness', 'Seamless Handoff', 'Call Recording']
    }
};

const VideoContext = createContext<VideoContextType | undefined>(undefined);

export function VideoProvider({ children }: { children: React.ReactNode }) {
    const [videos, setVideos] = useState<Record<string, VideoData>>(defaultVideos);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        loadVideosFromDatabase();
    }, []);

    const loadVideosFromDatabase = async () => {
        try {
            if (!supabase) {
                setLoading(false);
                return;
            }

            const { data, error } = await supabase
                .from('video_metadata')
                .select('*');

            if (error) throw error;

            if (data && data.length > 0) {
                const videosMap: Record<string, VideoData> = {};
                data.forEach((video: any) => {
                    videosMap[video.id] = {
                        id: video.id,
                        title: video.title,
                        description: video.description,
                        videoUrl: video.video_url,
                        thumbnailUrl: video.thumbnail_url,
                        stats: video.stats,
                        features: video.features
                    };
                });
                setVideos(videosMap);
            }
        } catch (error) {
            console.error('Error loading videos:', error);
        } finally {
            setLoading(false);
        }
    };

    const updateVideo = (id: string, data: Partial<VideoData>) => {
        setVideos(prev => ({
            ...prev,
            [id]: { ...prev[id], ...data }
        }));
    };

    const saveVideo = async (id: string, data?: Partial<VideoData>): Promise<{ success: boolean; error?: string }> => {
        try {
            if (!supabase) {
                return { success: false, error: 'Database not available' };
            }

            const video = data ? { ...videos[id], ...data } : videos[id];
            if (!video) {
                return { success: false, error: 'Video not found' };
            }

            const { error } = await supabase
                .from('video_metadata')
                .update({
                    video_url: video.videoUrl,
                    thumbnail_url: video.thumbnailUrl,
                    updated_at: new Date().toISOString()
                })
                .eq('id', id);

            if (error) throw error;

            return { success: true };
        } catch (error) {
            console.error('Error saving video:', error);
            return {
                success: false,
                error: error instanceof Error ? error.message : 'Failed to save video'
            };
        }
    };

    return (
        <VideoContext.Provider value={{ videos, updateVideo, saveVideo, loading }}>
            {children}
        </VideoContext.Provider>
    );
}

export function useVideos() {
    const context = useContext(VideoContext);
    if (context === undefined) {
        throw new Error('useVideos must be used within a VideoProvider');
    }
    return context;
}
