/*
  # Create video metadata table

  1. New Tables
    - `video_metadata`
      - `id` (text, primary key) - video section identifier (e.g., 'chat-agents')
      - `title` (text) - video section title
      - `description` (text) - video section description
      - `video_url` (text) - URL to the video file or embed
      - `thumbnail_url` (text, optional) - URL to video thumbnail
      - `stats` (jsonb) - video stats (duration, quality, delivery)
      - `features` (text[]) - array of feature strings
      - `updated_at` (timestamptz) - last update timestamp
      - `created_at` (timestamptz) - creation timestamp

  2. Security
    - Enable RLS on `video_metadata` table
    - Add policy for public read access (anyone can view videos)
    - Add policy for authenticated admin users to update videos

  3. Initial Data
    - Insert default video sections with placeholder data
*/

CREATE TABLE IF NOT EXISTS video_metadata (
  id text PRIMARY KEY,
  title text NOT NULL,
  description text NOT NULL,
  video_url text NOT NULL,
  thumbnail_url text,
  stats jsonb NOT NULL DEFAULT '{"duration": "", "quality": "", "delivery": ""}'::jsonb,
  features text[] NOT NULL DEFAULT ARRAY[]::text[],
  updated_at timestamptz DEFAULT now(),
  created_at timestamptz DEFAULT now()
);

ALTER TABLE video_metadata ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can view video metadata"
  ON video_metadata
  FOR SELECT
  TO anon, authenticated
  USING (true);

CREATE POLICY "Authenticated users can update video metadata"
  ON video_metadata
  FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Authenticated users can insert video metadata"
  ON video_metadata
  FOR INSERT
  TO authenticated
  WITH CHECK (true);

-- Insert default video sections
INSERT INTO video_metadata (id, title, description, video_url, stats, features)
VALUES 
  (
    'chat-agents',
    'Chat Agents',
    'Intelligent WhatsApp chatbots that seamlessly interact with humans, providing instant support and engagement.',
    'https://assets.mixkit.co/videos/preview/mixkit-virtual-reality-game-display-1167-large.mp4',
    '{"duration": "24/7", "quality": "Auto", "delivery": "Instant"}'::jsonb,
    ARRAY['Natural Language Processing', 'Multi-language Support', 'Automated Workflows', 'CRM Integration']
  ),
  (
    'ai-avatars',
    'AI Avatars',
    'Lifelike AI avatars that can present your content with human-like expressions and gestures.',
    'https://assets.mixkit.co/videos/preview/mixkit-woman-wearing-a-vr-headset-interacting-with-data-43687-large.mp4',
    '{"duration": "Custom", "quality": "4K", "delivery": "24 Hours"}'::jsonb,
    ARRAY['Photorealistic Rendering', 'Customizable Appearance', 'Lip-sync Technology', 'Brand Consistency']
  ),
  (
    'video-ads',
    'AI Generated Video Ads',
    'High-converting video advertisements generated by AI, tailored to your target audience.',
    'https://assets.mixkit.co/videos/preview/mixkit-digital-animation-of-a-city-interface-965-large.mp4',
    '{"duration": "15-60s", "quality": "1080p", "delivery": "48 Hours"}'::jsonb,
    ARRAY['Targeted Messaging', 'A/B Testing Ready', 'Viral Potential', 'Cost-Effective']
  ),
  (
    'voice-agents',
    'Voice Calling Agents',
    'Sophisticated voice agents capable of handling complex customer conversations over the phone.',
    'https://assets.mixkit.co/videos/preview/mixkit-customer-service-woman-working-on-computer-43682-large.mp4',
    '{"duration": "Unlimited", "quality": "HD Voice", "delivery": "Real-time"}'::jsonb,
    ARRAY['Sentiment Analysis', 'Context Awareness', 'Seamless Handoff', 'Call Recording']
  )
ON CONFLICT (id) DO NOTHING;
